spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: local

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}